version: "3"

services:
    app:
        build:
            context: .
        ports: 
            - "80"
        volumes: 
            - ./app:/app
        command: >
            sh -c "pyhton manage.py runserver 0.0.0.0:80"
        environment: 
            - VIRTUAL_HOST=django.dd4f.sh
        